### ISSUE TITLE
Automate certificate update process

### ISSUE THREAD

**Issue by dustsigns** [CenterForSecureEnergyInformatics/data-compressor-buildbot#2]
The current certificate update process requires several manual steps and has been announced to be deprecated very soon. Thus, an alternative solution that allows for automated certificate updates, e.g., via LetsEncrypt, must be implemented and the documentation must be updated accordingly.

**Comment by brhat** [comment]
Implemented automatic certificate renewal (using Let's Encrypt) in the pending pull request.
